# Usage:
#   python compare.py --config configs/example.yaml
#   torchrun --standalone --nproc_per_node=2 train_ddp.py --config configs/example.yaml

experiment_name: compare_reward_signals_3
epochs: 40
batch: 16
lr_lm: 0.0003
use_wandb: true
model_type: hf_pretrained
hf_model_name: openai-community/gpt2
training_algorithm: grpo
easy_samples: 20000
hard_samples: 4000
use_single_dataset: true 