experiment_name: gptxl_freeze_router_ablation
epochs: 10
global_batch_size: 64
pool_mult: 10
lr_lm: 0.0003
use_wandb: true
max_chunks: 500000
model_type: hf_pretrained
hf_model_name: openai-community/gpt2-xl
use_original_sequence: false
sentence_embedder_dim: 768
dataset_list: ["roneneldan/TinyStories", "Geralt-Targaryen/openwebtext2"]
dataset_proportions: [0.7, 0.3]
