experiment_name: opus_gpt2xl_muon_fineweb_random_baseline
model_type: hf_pretrained
hf_model_name: openai-community/gpt2-xl
lm_optimizer: muon
lr_lm: 0.002
lr_muon: 0.01
grad_clip_norm: 1.0
epochs: 1
block: 256
global_batch_size: 640
pool_mult: 10
max_chunks: 130000000
max_tokens: 30000000000
dataset_list: ["HuggingFaceFW/fineweb-100BT"]
dataset_proportions: [1]
save_model_at_end: true
use_wandb: true
run_random_batch_baseline: true
